'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import TargetShell from '@/components/TargetShell';
import PageHero from '@/components/PageHero';
import FinalCta from '@/components/FinalCta';
import { ArrowRight, CheckCircle2, Monitor, Bus, Layers, Palette, Cpu, Sparkles } from 'lucide-react';

const solutionPillars = [
  {
    id: 'display',
    title: 'Display Advertising (DOOH)',
    icon: Monitor,
    tagline: 'High dwell-time screens in daily lifestyle environments',
    image: '/images/display.jpg',
    href: '/locations',
    summary:
      'Place your brand inside high-definition digital screens across restaurants, luxury residential lift lobbies, corporate tech parks, shopping malls, fitness centres, play zones, and PG clusters.',
    metrics: [
      { label: 'Screen Opportunity', value: '4,500+' },
      { label: 'Avg Dwell Time', value: '25–45 min' },
      { label: 'Metropolitan Clusters', value: 'Key Hubs' },
    ],
    features: [
      'Captive dining room and waiting lounge audiences',
      'Unavoidable daily residential elevator lobby encounters',
      'Corporate decision-maker reach during business hours',
      'Weekend shopping mall retail intent surges',
    ],
  },
  {
    id: 'moving',
    title: 'Advertising on the Move',
    icon: Bus,
    tagline: 'City-wide mobile visibility following arterial commuter routes',
    image: '/images/streets.jpg',
    href: '/advertising-on-the-move',
    summary:
      'Turn urban transportation into high-impact mobile billboards. Full and semi wraps on autorickshaws, fleet cabs, metropolitan buses, route-targeted mobile vans, and eye-level bus shelters.',
    metrics: [
      { label: 'Vehicle Formats', value: '6 Types' },
      { label: 'Route Coverage', value: 'Neighbourhood & Arterial' },
      { label: 'Street Attention', value: 'Eye-Level' },
    ],
    features: [
      'Autos weaving through dense residential lanes & markets',
      'Branded cabs circulating across IT corridors and airports',
      'Large-format buses dominating high-traffic arterial junctions',
      'Routable mobile vans for roadshows and ground activations',
    ],
  },
  {
    id: 'offline',
    title: 'Offline & Print Distribution',
    icon: Layers,
    tagline: 'Direct-to-doorstep physical media delivered with area discipline',
    image: '/images/flyers.jpg',
    href: '/offline-print',
    summary:
      'Get physical branding directly into hands and living rooms. Supervised offline flyer drops, official morning newspaper inserts, quick-commerce dark store bag drops, and pharmacy covers.',
    metrics: [
      { label: 'Distribution Hubs', value: 'Dark Stores & Routes' },
      { label: 'Household Entry', value: 'Direct In-Home' },
      { label: 'Tracking', value: 'Area-Wise Discipline' },
    ],
    features: [
      'Area-targeted flyer distribution at metro hubs and societies',
      'Verified newspaper inserts that reach breakfast tables',
      'Quick-commerce delivery partner collateral insertion',
      'High-utility reusable pharmacy covers with prolonged life',
    ],
  },
  {
    id: 'creative',
    title: 'Print & Creative Design',
    icon: Palette,
    tagline: 'Studio-crafted visuals engineered for maximum real-world recall',
    image: '/images/creative.jpg',
    href: '/print-creative',
    summary:
      'From single brochures to multi-format retail campaigns, our creative team designs production-ready outdoor collateral, magazine spreads, event standees, pole kiosks, and social assets.',
    metrics: [
      { label: 'Design Asset Types', value: '12+ Formats' },
      { label: 'Print Readiness', value: '100% Pre-Press' },
      { label: 'Brand Consistency', value: 'Physical to Digital' },
    ],
    features: [
      'Brochure, catalogue and product presentation design',
      'Standees, roll-up banners and on-ground stall branding',
      'Neighbourhood pole kiosks and high-impact no-parking boards',
      'Social media creative kits matching real-world signage',
    ],
  },
  {
    id: 'digital',
    title: 'Website, Development & AI',
    icon: Cpu,
    tagline: 'The conversion infrastructure where real-world curiosity lands',
    image: '/images/website.jpg',
    href: '/digital',
    summary:
      'Ensure the demand generated by your offline ads converts effortlessly online. We build high-speed business sites, e-commerce storefronts, 24/7 AI lead-capture chatbots, and managed cloud hosting.',
    metrics: [
      { label: 'Uptime & Security', value: '99.9%' },
      { label: 'Mobile Optimization', value: 'Core Web Vitals' },
      { label: 'AI Lead Capture', value: '24/7 Automated' },
    ],
    features: [
      'Modern, editorial business websites tailored for local conversions',
      'Fast e-commerce catalogues with frictionless payment flows',
      'Automated AI conversational assistants for instant response',
      'Ongoing managed cloud hosting, backups and SEO maintenance',
    ],
  },
];

export default function SolutionsPage() {
  const [activeTab, setActiveTab] = useState('all');

  const filteredPillars =
    activeTab === 'all'
      ? solutionPillars
      : solutionPillars.filter((p) => p.id === activeTab);

  return (
    <TargetShell>
      {/* 1. Hero */}
      <PageHero
        eyebrow="Solutions / Advertising Ecosystem"
        title="One network. Multiple surfaces. Total local recall."
        copy="Mr. Ads combines indoor digital screens, moving city transit, doorstep print distribution, studio creative design, and modern digital web solutions under a single, cohesive campaign partner."
      />

      {/* 2. Interactive Channel Filter Tabs */}
      <section className="border-b border-line bg-[#080808]">
        <div className="container-site py-8 sm:py-10">
          <div className="flex items-center gap-2 overflow-x-auto pb-2 scrollbar-none">
            <button
              onClick={() => setActiveTab('all')}
              className={`px-4 py-2 rounded-lg text-[13px] font-medium transition-all shrink-0 ${
                activeTab === 'all'
                  ? 'bg-brand text-white shadow-md shadow-brand/20'
                  : 'bg-white/[0.04] text-mute hover:text-paper hover:bg-white/[0.08]'
              }`}
            >
              All Solutions
            </button>
            {solutionPillars.map((p) => (
              <button
                key={p.id}
                onClick={() => setActiveTab(p.id)}
                className={`px-4 py-2 rounded-lg text-[13px] font-medium transition-all shrink-0 ${
                  activeTab === p.id
                    ? 'bg-brand text-white shadow-md shadow-brand/20'
                    : 'bg-white/[0.04] text-mute hover:text-paper hover:bg-white/[0.08]'
                }`}
              >
                {p.title.split(' ')[0]} {p.title.split(' ')[1]}
              </button>
            ))}
          </div>
        </div>
      </section>

      {/* 3. Detailed Solution Showcases */}
      <section className="border-b border-line bg-[#0D0D0D]">
        <div className="container-site py-20 md:py-28 space-y-24">
          {filteredPillars.map((pillar, idx) => {
            const IconComponent = pillar.icon;
            const isReversed = idx % 2 === 1;

            return (
              <div
                key={pillar.id}
                id={pillar.id}
                className="scroll-mt-28 grid gap-12 lg:grid-cols-12 items-center"
              >
                {/* Visual Column */}
                <div
                  className={`lg:col-span-6 ${
                    isReversed ? 'lg:order-2' : ''
                  }`}
                >
                  <div className="relative rounded-2xl overflow-hidden border border-white/10 shadow-2xl bg-black group">
                    <div className="img-zoom aspect-[16/10]">
                      <img
                        src={pillar.image}
                        alt={pillar.title}
                        className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105"
                      />
                    </div>
                    <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-black/20 pointer-events-none" />

                    <div className="absolute bottom-4 left-4 right-4 flex items-center justify-between pointer-events-none">
                      <span className="px-3 py-1 rounded-full bg-black/75 backdrop-blur-md border border-white/10 text-[11px] font-semibold tracking-wider text-paper uppercase">
                        {pillar.tagline}
                      </span>
                    </div>
                  </div>
                </div>

                {/* Content Column */}
                <div
                  className={`lg:col-span-6 flex flex-col justify-between ${
                    isReversed ? 'lg:order-1' : ''
                  }`}
                >
                  <div>
                    <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white/[0.04] border border-white/10 text-[11px] font-semibold text-brand tracking-wider uppercase mb-4">
                      <IconComponent size={14} />
                      <span>Channel Overview</span>
                    </div>

                    <h2 className="font-serif text-[30px] sm:text-[38px] leading-tight tracking-tight text-paper font-normal">
                      {pillar.title}
                    </h2>

                    <p className="mt-4 text-[15px] sm:text-[16px] leading-relaxed text-mute">
                      {pillar.summary}
                    </p>

                    {/* Metric Badges */}
                    <div className="mt-6 grid grid-cols-3 gap-3 p-4 rounded-xl border border-white/[0.06] bg-white/[0.02]">
                      {pillar.metrics.map((m) => (
                        <div key={m.label}>
                          <p className="font-serif text-[18px] sm:text-[20px] font-bold text-paper">
                            {m.value}
                          </p>
                          <p className="mt-0.5 text-[11px] text-[#888888] uppercase tracking-wider">
                            {m.label}
                          </p>
                        </div>
                      ))}
                    </div>

                    {/* Key Features Bullet Points */}
                    <ul className="mt-6 space-y-2.5">
                      {pillar.features.map((feat) => (
                        <li key={feat} className="flex items-start gap-2.5 text-[14px] text-mute">
                          <CheckCircle2 size={16} className="text-brand shrink-0 mt-0.5" />
                          <span className="text-[#D8D4CE]">{feat}</span>
                        </li>
                      ))}
                    </ul>
                  </div>

                  <div className="mt-8 pt-6 border-t border-white/[0.06] flex items-center gap-4">
                    <Link
                      href={pillar.href}
                      className="btn-arrow inline-flex items-center gap-2 rounded-lg bg-brand hover:bg-brand-hover px-5 py-2.5 text-[13px] font-semibold text-paper shadow-md transition-all"
                    >
                      <span>Explore Channel Page</span>
                      <ArrowRight size={13} />
                    </Link>

                    <Link
                      href="/pricing"
                      className="inline-flex items-center gap-1.5 rounded-lg border border-white/10 hover:border-white/20 bg-white/[0.02] hover:bg-white/[0.05] px-4 py-2.5 text-[13px] font-medium text-paper transition-all"
                    >
                      <span>Get Plan</span>
                    </Link>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      </section>

      {/* 4. Multi-Channel Synergy Strip */}
      <section className="border-b border-line bg-[#080808]">
        <div className="container-site py-16 sm:py-20">
          <div className="rounded-2xl border border-brand/30 bg-gradient-to-r from-brand/10 via-transparent to-brand/5 p-8 sm:p-12 flex flex-col md:flex-row items-center justify-between gap-8">
            <div className="max-w-xl">
              <span className="inline-flex items-center gap-2 text-[11px] font-bold text-brand uppercase tracking-widest mb-2">
                <Sparkles size={13} /> Synchronized Flights
              </span>
              <h3 className="font-serif text-[28px] sm:text-[34px] font-normal leading-tight text-paper">
                The Compound Multiplier Effect
              </h3>
              <p className="mt-3 text-[14.5px] leading-relaxed text-mute">
                When an audience member spots your branded bus in the morning, sees your digital display during dinner, and receives your brochure at their doorstep, trust compounds 3x faster than any single-medium buy.
              </p>
            </div>

            <Link
              href="/pricing"
              className="btn-arrow inline-flex items-center justify-center gap-2.5 rounded-lg bg-brand hover:bg-brand-hover px-7 py-3.5 text-[14px] font-semibold text-paper shadow-lg shadow-brand/20 transition-all shrink-0"
            >
              <span>Build a Combined Media Plan</span>
              <ArrowRight size={15} />
            </Link>
          </div>
        </div>
      </section>

      {/* 5. Final CTA */}
      <FinalCta
        title="Ready to Build Your Local Advertising Strategy?"
        copy="Tell us who you need to reach and where — we will prepare a complete media plan combining the right screens, transit routes, and physical distribution."
      />
    </TargetShell>
  );
}
